archives:
  - id: goserve
    builds:
      - goserve
    files: []
changelog:
  use: github-native
builds:
  - id: goserve
    main: ./cmd/goserve
    binary: goserve
    flags:
      - -trimpath
    ldflags:
      - -s -w -extldflags '-static' -X github.com/cmgsj/goserve/internal/version.version={{.Version}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
