version: 2
archives:
  - id: goserve
    builds:
      - goserve
    files:
      - "bin/*"
changelog:
  use: github-native
builds:
  - id: goserve
    binary: goserve
    flags:
      - -trimpath
    ldflags:
      - -s -w -extldflags '-static' -X github.com/cmgsj/goserve/pkg/cmd/goserve.version={{.Version}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
