name: Test

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Test Code
        run: |
          source .envrc
          make tools
          make tidy
          make fmt
          make generate
          make test

      - name: Generate Docs
        run: |
          make build version=docs
          bin/goserve --exclude='^(\.git|bin)$' --port 1234 . &>/dev/null &
          sleep 1
          curl -sSL "http://localhost:1234" >docs/index.html
          kill -9 %1

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "generate code"
